# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
        #group: Blog
            - { name: sonata.admin, manager_type: orm, group: Blog ,label: Category, icon: "<i class='fa fa-home'></i>" }

    admin.blogpost:
        class: AppBundle\Admin\BlogPostAdmin
        arguments: [~, AppBundle\Entity\BlogPost, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Blog ,label: BlogPost }